version: "3.7"
services:
  backend:
    build:
      context: backend
      target: development
    secrets:
      - app_crt
      - app_key
    env_file:
      - .env
    networks: 
      - app_net

  client:
    build:
      context: client
      # target: development
    secrets:
      - credential
    command: sleep infinity
    # depends_on:
      # - backend
    env_file:
      - .env
    networks: 
      - app_net

  proxy:
    build:
      context: proxy
      target: development
    command: sleep infinity
    networks: 
      - app_net

secrets:
  app_crt:
    file: secrets/credential/certs/web/app.crt
  app_key:
    file: secrets/credential/certs/web/app.key
  root_pem:
    file: secrets/credential/certs/local/boot.pem
  root_key:
    file: secrets/credential/certs/local/boot.key
networks:
    app_net:
        external: true