version: "3.7"
services:
  backend:
    build:
      context: backend
      target: development
      args:
        - name=value
    depends_on:
      - proxy
    secrets:
      - credential
    env_file:
      - .env
    networks: 
      - app_net

  client:
    build:
      context: client
      target: development
    command: sleep infinity
    secrets:
      - credential
    depends_on:
      - backend
      - proxy
    env_file:
      - .env
    networks: 
      - app_net

  proxy:
    build:
      context: proxy
      target: development
    networks: 
      - app_net

secrets:
  credential:
    file: secrets/credential/test.tls

networks:
    app_net:
        external: true