version: "3.7"
services:
  backend:
    build:
      context: backend
      target: development
    env_file:
      - .env
    secrets:
      - app_crt
      - app_key
    networks: 
      - app_net

  client:
    build:
      context: client
      target: development
    command: sleep infinity
    secrets:
      - app_crt
      - app_key
    env_file:
      - .env
    depends_on:
      - backend
      - proxy
    networks: 
      - app_net

  proxy:
    build:
      context: proxy
      target: development
    networks: 
      - app_net
    secrets:
      - app_crt
      - app_key

secrets:
  app_crt: 
    file: secrets/certs/web/app.crt
  app_key: 
    file: secrets/certs/web/app.key
  boot.key:
    file: secrets/certs/local/boot.key
  boot.pem:
    file: secrets/certs/local/boot.pem


networks:
    app_net:
        external: true